version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
      - "4444:4444"

  tracker-api:
    build: .
    container_name: tracker-api
    ports:
      - "8080:8080"
    depends_on:
      - selenium-chrome
    environment:
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - ./logs:/app/logs

networks:
  default:
    driver: bridge
