version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  tracker-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - selenium
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge